// chapter 1 ALERTS...
// 1.
// alert("Welcome to my website sir/madam");
// 2.
// alert("Error! Please enter a valid password.");
// 3.
// alert("Welcome to js land...\r\nHappy Coding!");
// 4.
// alert("Welcome to js land...");
// 5.
// alert("Happy Coding!");
// 6.
// document.write("Hello... I can run JS through my web browser's console");

// chapter 2 VARIABLES FOR STRING...
// 1.
// var userName;
// 2.
// var myName = "syed hassan hussain";
// 3.
// var message = "hello world";
// alert(message);
// 4.
// var students = "Name: Hassan";
// var age = "age: " + 15 + " years old";
// var address = "course: Certificate mobile application development";
// alert(students + "\r\n" + age + "\r\n" + address);
// 5.
// var a = "PIZZA" + "\r\n" + "PIZZ" + "\r\n" + "PIZ" + "\r\n" + "PI" + "\r\n" + "P"
// alert(a)
// 6.
// var email = "example@example.com"
// alert("My email address is " + email)
// 7.
// var book = "A smarter way to learn JavaScript"
// alert("I am trying to learn from the book " + book)
// 8.
// document.write("Yah! I can write HTML content through javascript")
// 9.
// var abc = "“▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬”"
// alert(abc)

// chapter 3 VARIABLE FOR NUMBERS...
// 1.
// var age = 15
// alert("I am " + age + " years old" )
// 2.
// var visit = "you have visites this site " + 14 + " times"
// alert(visit)
// 3.
// var birthYear = 1990
// document.write("My birth year is " + birthYear )
// document.write(typeof birthYear)
// 4.
// var name = "john Doe"
// var product = "T-shirt(s)"
// var quantity = 5
// document.write(name + " ordered "  + quantity + product + " on XYZ clothing store")

// chapter 4 VARIABLES NAMES LEGAL AND ILLEGAL...
// 1.
// var example, example1, example2 = 'hello'
// console.log(example2)
// 2.
// var greet12 = 'legal'
// var greet = 'legal'
// var $greet = 'legal'
// var greet12_3 = 'legal'
// 3.
// var 123 = 'illegal'
// var ha d = 'illegal'
// var for = 'illegal'
// 4.
// var rules = 'Rules for naming JS variables'
// document.write(rules + '<br>' + '<br>' + '<br>')
// 5.
// var names = 'letters'
// var names1 = 'number'
// var names2 = 'dollar sign'
// var names3 = 'underscores'
// document.write('Variable names can only contain ' + names + ', ' + names1 + ', ' + names2 + ', and ' + names3)
// 6.
// var sensitive = 'Sensitive'
// document.write('Variable names are case ' + sensitive)
// 7.
// var key = 'Keywords'
// document.write('Variable names should not be JS ' + key)

// // chapter 5 MATH EXPRESSIONS...
// 1.
// var num = 5
// var num1 = 3
// var sum = num + num1
// document.write("Add of " + num1 + " and " + num + " is: " + sum)
// document.write("<br>")
// 2.
// var num = 5
// var num1 = 3
// var sub = num - num1
// document.write("Sub of " + num1 + " and " + num + " is: " + sub)
// document.write("<br>")
// 2.a
// var num = 5
// var num1 = 3
// var mul = num * num1
// document.write("Multiply of " + num1 + " and " + num + " is: " + mul)
// document.write("<br>")
// 2.b
// var num = 5
// var num1 = 3
// var div = num / num1
// document.write("Divide of " + num1 + " and " + num + " is: " + div)
// document.write("<br>")
// 2.c
// var num = 5
// var num1 = 3
// var div = num % num1
// document.write("Modulus of " + num1 + " and " + num + " is: " + div)
// document.write("<br>")
// 3.
// var a = "Value after variable declaration is undefined"
// document.write(a)
// document.write("<br>")
// 3.a
// var b = 5
// document.write("Initial value: " + b)
// document.write("<br>")
// 3.b
// document.write("Value after increment is: " + ++b)
// document.write("<br>")
// 3.c
// b = 13
// document.write("Value after addition is: " + b )
// document.write("<br>")
// 3.d
// document.write("Value after decrement is: " + --b)
// document.write("<br>")
// 3.e
// document.write("The remainder is: " + b % 3)
// 4.
// var ticketPrice = 5
// document.write("Total cost to buy " + ticketPrice + " tickets to a movie is " + ticketPrice * 600 + "PKR")
// 5.
// document.write(4 + " x " + 1 + " = " + 4*1)
// document.write("<br>")
// document.write(4 + " x " + 2 + " = " + 4*2)
// document.write("<br>")
// document.write(4 + " x " + 3 + " = " + 4*3)
// document.write("<br>")
// document.write(4 + " x " + 4 + " = " + 4*4)
// document.write("<br>")
// document.write(4 + " x " + 5 + " = " + 4*5)
// document.write("<br>")
// document.write(4 + " x " + 6 + " = " + 4*6)
// document.write("<br>")
// document.write(4 + " x " + 7 + " = " + 4*7)
// document.write("<br>")
// document.write(4 + " x " + 8 + " = " + 4*8)
// document.write("<br>")
// document.write(4 + " x " + 9 + " = " + 4*9)
// document.write("<br>")
// document.write(4 + " x " + 10 + " = " + 4*10)

// 7.
// var price1 = 650;
// var price2 = 100;
// var item = 3;
// var item2 = 7;
// document.write("Price of item 1 is " + price1);
// document.write("<br>");
// document.write("Quantity of item 1 is " + item);
// document.write("<br>");
// 7.a
// document.write("Price of item 2 is " + price2);
// document.write("<br>");
// 7.b
// document.write("Quantity of item 2 is " + item2);
// document.write("<br>");
// 7.c
// document.write("Shipping charges " + 100);
// document.write("<br>");
// document.write("<br>");
// 7.d
// var mul = price1 * item;
// var mul1 = price2 * item2;
// var sum = mul + mul1 + 100;
// console.log(sum);
// 7.e
// document.write("Total cost of your order is " + sum);
// 8.
// var marks = 980;
// var obtained = 804;
// var per = obtained / marks * 100
// document.write("Total marks: " + marks)
// document.write("<br>")
// document.write("Marks obtained: " + obtained)
// document.write("<br>")
// document.write("Percentage " + per)
// document.write("<br>")

// chapter 6-9

// var a = 10;

// document.write("Result:");
// document.write("<br>");
// document.write("The value of a is: " + a);
// document.write("<br>");
// document.write("<br>");
// document.write("The value of ++a is: 11");
// document.write("<br>");
// document.write("Now the value of a is: " + ++a);
// document.write("<br>");
// document.write("<br>");
// document.write("The value of a++ is: 11");
// document.write("<br>");
// document.write("Now the value of a is: " + a++);
// document.write("<br>");
// document.write("<br>");
// document.write("The value of --a is: 11");
// document.write("<br>");
// document.write("Now the value of a is: " + --a);
// document.write("<br>");
// document.write("<br>");

// var a = 2,
//   b = 1;
// var result = --a - --b + ++b + b--;
//             //   1  -  0  +  1  +  1
// console.log(result)

// document.write(--a);
// document.write("<br>");
// document.write(--a - --b);
// document.write("<br>");
// document.write(--a - --b + ++b);
// document.write("<br>");
// document.write(--a - --b + ++b + b--);

// var userInput = prompt("Enter your name")
// alert("Welcome to you " + userInput )

// var num = +prompt("Enter a number to print its multiplication table, ");
// document.write('<table border = "1" cellspacing = "0"');
// for (var i = 1; i <= 10; i++) {
//   if (num === num) {
//     document.write(
//       "<tr><td>" + num + " x " + i + " = " + num * i + "</tr> </td>"
//     );
//   }
// }
// document.write("</table>");

// chapter 9-11

// var city = prompt("Enter your city")
// document.write("Welcome to city of " + city)

// var gender = prompt("Enter your gender");

// if (gender === "male") {
//   document.write("Good Morning Sir ");
// }
// else if(gender === "female"){
//     document.write("Good Morning Ma'am ");
// }


// chapter= 17-20 ARRAY...

// var arr = [
//     [""]
//     [""]
//     [""]
// ];

// var arry = [
//     [0,1,2,3]
//     [1,0,1,2]
//     [2,1,0,1]
// ]

// for(var i = 1; i <=10; i++){
// document.write(i + "<br>")
// }

// var userInput = +prompt("Enter a number to show its multiplication table");

// var userLength = +prompt("Enter lenght multiplication table");

// document.write('<table border = "1" cellspacing = "0"');

// for (var i = 1; i <= userLength; i++) {
//   document.write(
//     "<tr><td>" + userInput + " x " + i + " = " + userInput * i + "</tr></td>"
//   );
// }

// document.write("</table");

// var fruits = ["apple", "banana", "mango", "orange", "strawberry" ];

// document.write(fruits[0] + "<br>")
// document.write(fruits[1] + "<br>")
// document.write(fruits[2] + "<br>")
// document.write(fruits[3] + "<br>")
// document.write(fruits[4] + "<br>")

// document.write("Element at index 0 is " + fruits[0] + "<br>")
// document.write("Element at index 1 is " + fruits[1] + "<br>")
// document.write("Element at index 2 is " + fruits[2] + "<br>")
// document.write("Element at index 3 is " + fruits[3] + "<br>")
// document.write("Element at index 4 is " + fruits[4] + "<br>")

// var counting = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
// document.write('Counting:' + "<br>" + counting)
// document.write("<br>")
// document.write("<br>")

// var reverse = [1,2,3,4,5,6,7,8,9,10]
// reverse.reverse()
// document.write("Reverse Counting: " + "<br>" + reverse)
// document.write("<br>")
// document.write("<br>")

// document.write("Even: <br>")
// for(var i = 0; i <=20; i++){
//     if ( i % 2 === 0){
//         document.write(i + ",")
//     }
// }
// document.write("<br>")
// document.write("<br>")

// document.write("Odd: <br>")
// for(var x = 1; x <=20; x++){
//     if (x % 2 !== 0){
//         document.write(x + ",")
//     }
// }
// document.write("<br>")
// document.write("<br>")

// document.write("Series: <br>")
// for(var i = 1; i <=20; i++){
//     if ( i % 2 === 0){
//         document.write(i + "k,")
//     }
// }

// var userInput = prompt("Welcome to abc bakery. What do you want to order sir/ma'am")

// var bakery = ["cake", "apple pie", "cookies", "chips", "patties"]

// var flag = true

// for (var i = 0; i < bakery.length; i++){
//     if (userInput === bakery[i]){
//         flag = false
//         document.write("cookie is available at index " + i + " in our bakery")
//     }
// }
// if (flag){
//     document.write("We are sorry " + userInput + " is not available in our bakery")
// }

// var arr = [14, 58, 20, 77, 66, 82, 42, 67, 42, 4];
// var max = Math.max(...arr);
// document.write("Array items: " + arr + "<br>")
// document.write("The largest number is " + max )

// var arry = [1,2,8,9,45,65,78,98]
// var min = Math.min(...arry)
// document.write("Array items: " + arry + "<br>")
// document.write("The smallest number is " + min)

    // for(var i =1; i <= 100; i++){
    //     if(i % 5 === 0){
    //         document.write( i + "," )
    //     }
    // }

// chapter- 21-25

// var firstName = prompt("Enter your first name")
// var lastName = prompt("Enter your last name")
// var fullname = firstName + " " + lastName
// alert("Welcome to you " + fullname)

// var user = prompt("Enter your Favourite Mobile Phones")
// document.write("My favourite phone is: " + user + "<br>" + "Length of string: " + user.length)

//  var letters = "pakistani"
//  var let = letters.indexOf("n")
//  document.write("String: " + letters + "<br>" + "Index of 'n': " + let)

// var letters1 = "Hello world"
// var get = letters1.lastIndexOf("l")
//  document.write("String: " + letters1 + "<br>" + "Index of 'n': " + get)

// var char = "pakistani"
// var charr = char.charAt(5)
// document.write("String: " + char + "<br>" + "Character at index 5:" + charr)

// var city = "Hyderabad"
// var textRep = city.replace("Hyder", "Islam")
// document.write("City: " + city + "<br>" + "After replacement: " + textRep)

// var message = "Ali and Sami are best friends. They play cricket and football together.";
// var rep = message.replace(/and/g, "&")
// document.write(rep)

// var number = "472"
// document.write("Value: " + number + "<br>" + "Type: " + typeof number + "<br>")
// var number1 = 472
// document.write("Value: " + number1 + "<br>" + "Type: " + typeof number1)

// fuuction...

// 1
// function currentDate() {
//   var date = new Date();
//   document.write(date);
// }
// currentDate();

// 2
// function fullname() {
//   var firstName = prompt("Enter your first name");
//   var lastName = prompt("Enter your last name");
//   var name = firstName + " " + lastName;
//   document.write(name);
// }
// fullname();

// 3
// function numbers() {
//   var num1 = +prompt("Enter first value");
//   var num2 = +prompt("Enter second value");
//   var add = num1 + num2;
//   return add;
// }
// document.write(numbers());

// 4
// var num1 = +prompt("Enter first value");
// var oper = prompt("Enter operator");
// var num2 = +prompt("Enter second value");
// function calculator(num1, oper, num2) {
//   if (oper === "+") {
//     return num1 + num2;
//   } else if (oper === "-") {
//     return num1 - num2;
//   } else if (oper === "*") {
//     return num1 * num2;
//   } else if (oper === "/") {
//     return num1 / num2;
//   } else {
//     return "sorry! Enter correct operator";
//   }
// }
// document.write(calculator(num1, oper, num2));

// 5
// function abc(a, b) {
//   document.write(a + b);
// }
// abc(5, 5);

// 7
// function number() {
//   var firstNum = +prompt("Enter start number");
//   var endNum = +prompt("Enter end number");

//   for (var i = firstNum; i <= endNum; i++) {
//     document.write(i + "<br>");
//   }
// }
// number();

// 9
// function rectangle(width, height) {
//   var area = width * height;
//   console.log(area);
// }
// rectangle(10, 5);

// 10
// Write a JavaScript function that checks whether a passed string is palindrome or not?

// function check_Palindrome(str_entry){
// Change the string into lower case and remove  all non-alphanumeric characters
//  var cstr = str_entry.toLowerCase().replace(/[^a-zA-Z0-9]+/g,'');
// var ccount = 0;
// Check whether the string is empty or not
// if(cstr==="") {
//   console.log("Nothing found!");
//   return false;
// }
// Check if the length of the string is even or odd
// if ((cstr.length) % 2 === 0) {
//   ccount = (cstr.length) / 2;
// } else {
// If the length of the string is 1 then it becomes a palindrome
// if (cstr.length === 1) {
//   console.log("Entry is a palindrome.");
//   return true;
// } else {
// If the length of the string is odd ignore middle character
//     ccount = (cstr.length - 1) / 2;
//   }
// }
// Loop through to check the first character to the last character and then move next
// for (var x = 0; x < ccount; x++) {
// Compare characters and drop them if they do not match
//     if (cstr[x] != cstr.slice(-1-x)[0]) {
//       console.log("Entry is not a palindrome.");
//       return false;
//     }
//   }
//   console.log("The entry is a palindrome.");
//   return true;
// }
// check_Palindrome(prompt('enter plaindram'));
// check_Palindrome('nurses run');
// check_Palindrome('fox');

// 11
// function upperCase(word) {
//   var array = word.split(" ");
//   var array1 = [];
//   for (var i = 0; i < array.length; i++) {
//     array1.push(array[i].charAt(0).toUpperCase() + array[i].slice(1));
//   }
//   return array1.join(" ");
// }
// console.log(upperCase(prompt("Enter any thing")));

// 12

function findLongestWord(str) {
    var strSplit = str.split(" ");
    var longestWord = '';
    for (var i = 0; i < strSplit.length; i++) {
      if (strSplit[i].length > longestWord.length) {
        longestWord = strSplit[i];
      }
    }
    return longestWord;
  }
  console.log(findLongestWord("The quick brown fox jumping over the lazy dog"));
  