// chapter 1

// alert("Good Morning Js");

// alert("Error! Please enter a valid password.");

// alert("Welcome to js land...\r\nHappy Coding!");

// alert("Welcome to js land...");

// alert("Happy Coding!");

// console.log("Hello... I can run JS through my web browser's console");

// chapter 2

// var userName;

// var myName = "syed hassan hussain";

// var message = "hello world";
// alert(message);

// var students = "Name: Hassan";
// var age = "age: " + 15 + " years old";
// var address = "course: Certificate mobile application development";
// alert(students + "\r\n" + age + "\r\n" + address);

// var a = "PIZZA" + "\r\n" + "PIZZ" + "\r\n" + "PIZ" + "\r\n" + "PI" + "\r\n" + "P"
// alert(a)

// var email = "example@example.com"
// alert("My email address is " + email)

// var book = "A smarter way to learn JavaScript"
// alert("I am trying to learn from the book " + book)

// document.write("Yah! I can write HTML content through javascript")

// var abc = "“▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬”"
// alert(abc)

// chapter 3

// var age = 15
// alert("I am " + age + " years old" )

// var visit = "you have visites this site " + 14 + " times"
// alert(visit)

// var birthYear = 1990
// document.write("My birth year is " + birthYear ) 
// document.write(typeof birthYear)

// var name = "john Doe"
// var product = "T-shirt(s)"
// var quantity = 5
// document.write(name + " ordered "  + quantity + product + " on XYZ clothing store")

// chapter 5

// var num = 5
// var num1 = 3
// var sum = num + num1
// document.write("Add of " + num1 + " and " + num + " is: " + sum)
// document.write("<br>")

// var num = 5
// var num1 = 3
// var sub = num - num1
// document.write("Sub of " + num1 + " and " + num + " is: " + sub)
// document.write("<br>")

// var num = 5
// var num1 = 3
// var mul = num * num1
// document.write("Multiply of " + num1 + " and " + num + " is: " + mul)
// document.write("<br>")

// var num = 5
// var num1 = 3
// var div = num / num1
// document.write("Divide of " + num1 + " and " + num + " is: " + div)
// document.write("<br>")

// var num = 5
// var num1 = 3
// var div = num % num1
// document.write("Modulus of " + num1 + " and " + num + " is: " + div)
// document.write("<br>")

// var a = "Value after variable declaration is undefined"
// document.write(a)
// document.write("<br>")

// var b = 5
// document.write("Initial value: " + b)
// document.write("<br>")


// document.write("Value after increment is: " + ++b)
// document.write("<br>")

// b = 13
// document.write("Value after addition is: " + b )
// document.write("<br>")

// document.write("Value after decrement is: " + --b)
// document.write("<br>")

// document.write("The remainder is: " + b % 3)

// var ticketPrice = 5
// document.write("Total cost to buy " + ticketPrice + " tickets to a movie is " + ticketPrice * 600 + "PKR")

// document.write(4 + " x " + 1 + " = " + 4*1) 
// document.write("<br>")
// document.write(4 + " x " + 2 + " = " + 4*2) 
// document.write("<br>")
// document.write(4 + " x " + 3 + " = " + 4*3)
// document.write("<br>")
// document.write(4 + " x " + 4 + " = " + 4*4)
// document.write("<br>")
// document.write(4 + " x " + 5 + " = " + 4*5)
// document.write("<br>")
// document.write(4 + " x " + 6 + " = " + 4*6)
// document.write("<br>")
// document.write(4 + " x " + 7 + " = " + 4*7)
// document.write("<br>")
// document.write(4 + " x " + 8 + " = " + 4*8)
// document.write("<br>")
// document.write(4 + " x " + 9 + " = " + 4*9)
// document.write("<br>")
// document.write(4 + " x " + 10 + " = " + 4*10)

var price1 = 650
var price2 = 100
document.write("Price of item 1 is " + price1)
document.write("<br>")
document.write("Quantity of item 1 is " + 3)
document.write("<br>")

document.write("Price of item 2 is " + price2)
document.write("<br>")

document.write("Quantity of item 2 is " + 7)
document.write("<br>")

document.write("Total cost of your order is " + price1 * 3 * price2 * 7)
